name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: eslint & markdown

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v4
        with:
          globs: '**/*.md'
